=== ziaziek/TradexClient/src/main/resources/Menu.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Menu.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE menubar SYSTEM "Menu.dtd">

    <menubar>
    ...
    </menubar>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT menubar (menu)*>

<!--- Defines the main menu elements visible on the bar. -->
<!ELEMENT menu (item)*>
<!ATTLIST menu
    name CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT item (#PCDATA)>
<!ATTLIST item
    action ID #IMPLIED
  >

=== ziaziek/TradexClient/src/main/resources/Menu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE menu SYSTEM "Menu.dtd">
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->


<menubar>
    <menu name="File">
        <item action = "Connect">Connect</item>
        <item action = "Disconnect">Disconnect</item>
        <item action = "Exit">Exit</item>
    </menu>
    <menu name="Equities">
        <item action="showAvailableEquities">Show Available</item>
        <item action="reloadAvailableEquities">Reload Available</item>
        <item action="openChartWindow">Open Equity Chart Window</item>
    </menu>
    <menu name="Data">
        <item action="downloadData">Download</item>
        <item action="serverSettings">Server Settings</item>
    </menu>
    <menu name="Trade">
        <item action="placeOrder">Place Order</item>
        <item action="removeOrder">Remove Order</item>
        <item action="removaAllOrders">Remove All Orders</item>
        <item action="setOrderTrigger">Set Order Trigger</item>
        <item action="stopOrderTrigger">Stop Order Trigger</item>
    </menu>
    <menu name="Workspace">
        <item action="loadWorkspace">Load Workspace</item>
        <item action="saveWorkspace">Save Workspace</item>
        <item action="loadDefaultWorkspace">Load Default Workspace</item>
    </menu>
    <menu name="Help">
        <item action="helpAbout">About</item>
        <item action="helpIndex">Index</item>
    </menu>
</menubar>
